### ISSUE TITLE
Connection with Mongo and responses-tidy.rds file

### ISSUE THREAD

**Issue by ShivamPanchal** [departmentfortransport/janus-dashboard#1]
I was testing this  amazing applications, but found issues in how it uses Mongo and what is responses-tidy.rds file and it's not available as well.

**Comment by willbowditch** [comment]
If this is a bug, could you provide a minimal example of how to reproduce it (https://stackoverflow.com/help/mcve).

The responses-tidy.rds file is created by the script.

**Comment by ShivamPanchal** [comment]
By which script you created the responses-tidy.rds. That is the question,

**Comment by willbowditch** [comment]
See this file: [01-tidy-data.R](01-tidy-data.R)

```
# Variables colx_label are defined in 00-build.R
# Renames colum names to generic col1, col2, col3 for easier programming
responses_tidy <- read_csv("data/generic-data.csv") %>%
  rename_("col1" = col1_label,
          "col2" = col2_label,
          "col3" = col3_label) %>%
  mutate_all(as.character)

saveRDS(responses_tidy, "data/responses-tidy.rds")
```

You should run all the files in the root directory in order before the dashboard, as they prepare the data.
